version: '3,9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - ./dist:/app
      - /app/node_modules
    restart: on-failure
    command: >
        sh -c "node --watch main.js"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/cars?schema=public
      - JWT_SECRET=ewrfw#$
      - SHOP_ID=
      - PAYMENT_TOKEN=
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
